### ISSUE TITLE
Should work without DOM / window

### ISSUE THREAD

**Issue by austinhallock** [Zorium/zorium#45]
ReferenceError: window is not defined
  at new Router (/home/austin/dev/clay-mobile/node_modules/zorium/dist/zorium.js:361:6)
  at Object.module.exports.__bind (/home/austin/dev/clay-mobile/node_modules/zorium/dist/zorium.js:491:19)

**Comment by Zolmeister** [comment]
duplicate of #22

**Comment by austinhallock** [comment]
Can we get a quicker fix for that? So we can include modules that require zorium (eg User model on clay-mobile) inside of server.coffee

**Comment by Zolmeister** [comment]
Why do we need it inside of server.coffee?
Also, see if `observe = require 'zorium/observe'` works (though no guarantees on it being accepted)

**Comment by austinhallock** [comment]
Game model* for the getIcon method

**Comment by Zolmeister** [comment]
As commented in PR, add a TODO instead.
